
name = "content-skimmer"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Development/default environment variables - ALIGNED WITH SHARED CONFIG
[vars]
NODE_ENV = "development"
SERVICE_NAME = "content-skimmer"
LOG_LEVEL = "info"
DATA_SERVICE_URL = "http://localhost:3002"
CONTENT_STORE_SERVICE_URL = "http://localhost:3001"
AUTH_SERVICE_URL = "http://localhost:3003"
MEILISEARCH_HOST = "http://localhost:7700"
CORS_ORIGINS = "http://localhost:3000,http://localhost:3001"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"

[env.staging]
name = "content-skimmer-staging"
account_id = "0506015145cda87c34f9ab8e9675a8a9"

[env.staging.vars]
NODE_ENV = "staging"
SERVICE_NAME = "content-skimmer"
LOG_LEVEL = "info"
DATA_SERVICE_URL = "https://data-service-staging.tamylatrading.workers.dev"
CONTENT_STORE_SERVICE_URL = "https://content-staging.tamyla.com"
AUTH_SERVICE_URL = "https://auth-staging.tamyla.com"
MEILISEARCH_HOST = "https://search-staging.tamyla.com"
CORS_ORIGINS = "https://tamyla.com,https://*.tamyla.com,http://localhost:3000"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"

[env.production]
name = "content-skimmer"
account_id = "0506015145cda87c34f9ab8e9675a8a9"

[env.production.vars]
NODE_ENV = "production"
SERVICE_NAME = "content-skimmer"
LOG_LEVEL = "info"
DATA_SERVICE_URL = "https://data-service.tamylatrading.workers.dev"
CONTENT_STORE_SERVICE_URL = "https://content.tamyla.com"
AUTH_SERVICE_URL = "https://auth.tamyla.com"
MEILISEARCH_HOST = "https://search.tamyla.com"
CORS_ORIGINS = "https://tamyla.com,https://*.tamyla.com"
MAX_FILE_SIZE = "26214400"
ALLOWED_FILE_TYPES = "image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,video/webm,audio/mpeg,audio/wav"

# Secrets to be set via: wrangler secret put <name>
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# MEILIS_MASTER_KEY
# DATA_SERVICE_API_KEY
# WEBHOOK_SECRET
# AUTH_JWT_SECRET

# Cloudflare bindings (if using Vectorize)
# [[vectorize]]
# binding = "VECTORIZE"
# index_name = "content-embeddings"

# Queue binding (if using Cloudflare Queues for events)
# [[queues.producers]]
# queue = "content-processing"
# binding = "CONTENT_QUEUE"
